# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'welcomescreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.NonModal)
        Dialog.resize(1669, 990)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Images/eye.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setLayoutDirection(QtCore.Qt.LeftToRight)
        Dialog.setStyleSheet("")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1671, 991))
        self.widget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.widget.setStyleSheet("background-color: #bbbbbb;")
        self.widget.setObjectName("widget")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(1340, 0, 341, 991))
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setStyleSheet("border-radius:20px ;\n"
"\n"
"color: rgb(242, 242, 242);\n"
"font: 14pt \"Ubuntu\";\n"
"\n"
"\n"
"background-color: #6a6a6a;")
        self.label_4.setObjectName("label_4")
        self.AdminPanel = QtWidgets.QPushButton(self.widget)
        self.AdminPanel.setEnabled(True)
        self.AdminPanel.setGeometry(QtCore.QRect(1350, 20, 161, 61))
        self.AdminPanel.setStyleSheet("border-radius:20px ;\n"
"\n"
"color: black;\n"
"font: 14pt \"Ubuntu\";\n"
"\n"
"background-color: #fdbb2d;\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../Images/seting.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.AdminPanel.setIcon(icon1)
        self.AdminPanel.setIconSize(QtCore.QSize(32, 32))
        self.AdminPanel.setObjectName("AdminPanel")
        self.pen = QtWidgets.QLabel(self.widget)
        self.pen.setGeometry(QtCore.QRect(10, 5, 410, 320))
        self.pen.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pen.setStyleSheet("border-style: outset;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.pen.setText("")
        self.pen.setObjectName("pen")
        self.logo = QtWidgets.QLabel(self.widget)
        self.logo.setGeometry(QtCore.QRect(1350, 780, 311, 191))
        self.logo.setStyleSheet("background-color:#cdcdcd;\n"
"border-radius:20px ;")
        self.logo.setText("")
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.open = QtWidgets.QPushButton(self.widget)
        self.open.setGeometry(QtCore.QRect(1530, 20, 131, 61))
        self.open.setStyleSheet("border-radius:20px ;\n"
"\n"
"color: black;\n"
"font: 14pt \"Ubuntu\";\n"
"\n"
"background-color: #fdbb2d;\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../Images/start.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.open.setIcon(icon2)
        self.open.setIconSize(QtCore.QSize(32, 32))
        self.open.setObjectName("open")
        self.comboBox = QtWidgets.QComboBox(self.widget)
        self.comboBox.setGeometry(QtCore.QRect(1350, 440, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.comboBox.setFont(font)
        self.comboBox.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.comboBox.setStyleSheet("border-radius:20px ;\n"
"\n"
"color: black;\n"
"font: 14pt \"Ubuntu\";\n"
"\n"
"background-color: #fdbb2d;\n"
"")
        self.comboBox.setObjectName("comboBox")
        self.comboBox_2 = QtWidgets.QComboBox(self.widget)
        self.comboBox_2.setGeometry(QtCore.QRect(1350, 330, 311, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.comboBox_2.setStyleSheet("border-radius:20px ;\n"
"\n"
"color: black;\n"
"font: 14pt \"Ubuntu\";\n"
"\n"
"background-color: #fdbb2d;\n"
"")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.pen_2 = QtWidgets.QLabel(self.widget)
        self.pen_2.setGeometry(QtCore.QRect(450, 5, 410, 320))
        self.pen_2.setStyleSheet("border-style: outset;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.pen_2.setText("")
        self.pen_2.setObjectName("pen_2")
        self.pen_3 = QtWidgets.QLabel(self.widget)
        self.pen_3.setGeometry(QtCore.QRect(890, 5, 410, 320))
        self.pen_3.setStyleSheet("border-style: outset;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.pen_3.setText("")
        self.pen_3.setObjectName("pen_3")
        self.pen_4 = QtWidgets.QLabel(self.widget)
        self.pen_4.setGeometry(QtCore.QRect(10, 335, 410, 320))
        self.pen_4.setStyleSheet("border-style: outset;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.pen_4.setText("")
        self.pen_4.setObjectName("pen_4")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(1350, 410, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color:white;\n"
"background-color: #6a6a6a;\n"
"font: 14pt \"Ubuntu\";")
        self.label.setObjectName("label")
        self.addCamera = QtWidgets.QPushButton(self.widget)
        self.addCamera.setGeometry(QtCore.QRect(1580, 440, 81, 41))
        self.addCamera.setStyleSheet("border-radius:20px ;\n"
"\n"
"color: black;\n"
"font: 14pt \"Ubuntu\";\n"
"\n"
"background-color: #fdbb2d;\n"
"")
        self.addCamera.setObjectName("addCamera")
        self.dltCamera = QtWidgets.QPushButton(self.widget)
        self.dltCamera.setGeometry(QtCore.QRect(1580, 690, 81, 41))
        self.dltCamera.setStyleSheet("border-radius:20px ;\n"
"\n"
"color: black;\n"
"font: 14pt \"Ubuntu\";\n"
"\n"
"background-color: #fdbb2d;\n"
"")
        self.dltCamera.setObjectName("dltCamera")
        self.cameraList = QtWidgets.QListWidget(self.widget)
        self.cameraList.setGeometry(QtCore.QRect(1350, 520, 221, 211))
        self.cameraList.setStyleSheet("border-radius:20px ;\n"
"\n"
"color: black;\n"
"font: 14pt \"Ubuntu\";\n"
"\n"
"background-color: #fdbb2d;\n"
"")
        self.cameraList.setObjectName("cameraList")
        self.pen_5 = QtWidgets.QLabel(self.widget)
        self.pen_5.setGeometry(QtCore.QRect(450, 335, 410, 320))
        self.pen_5.setStyleSheet("border-style: outset;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.pen_5.setText("")
        self.pen_5.setObjectName("pen_5")
        self.pen_6 = QtWidgets.QLabel(self.widget)
        self.pen_6.setGeometry(QtCore.QRect(890, 335, 410, 320))
        self.pen_6.setStyleSheet("border-style: outset;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.pen_6.setText("")
        self.pen_6.setObjectName("pen_6")
        self.pen_7 = QtWidgets.QLabel(self.widget)
        self.pen_7.setGeometry(QtCore.QRect(10, 665, 410, 320))
        self.pen_7.setStyleSheet("border-style: outset;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.pen_7.setText("")
        self.pen_7.setObjectName("pen_7")
        self.pen_8 = QtWidgets.QLabel(self.widget)
        self.pen_8.setGeometry(QtCore.QRect(450, 665, 410, 320))
        self.pen_8.setStyleSheet("border-style: outset;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.pen_8.setText("")
        self.pen_8.setObjectName("pen_8")
        self.pen_9 = QtWidgets.QLabel(self.widget)
        self.pen_9.setGeometry(QtCore.QRect(890, 665, 410, 320))
        self.pen_9.setStyleSheet("border-style: outset;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.pen_9.setText("")
        self.pen_9.setObjectName("pen_9")
        self.showCamera = QtWidgets.QPushButton(self.widget)
        self.showCamera.setGeometry(QtCore.QRect(1580, 640, 81, 41))
        self.showCamera.setStyleSheet("border-radius:20px ;\n"
"\n"
"color: black;\n"
"font: 14pt \"Ubuntu\";\n"
"\n"
"background-color: #fdbb2d;\n"
"")
        self.showCamera.setObjectName("showCamera")
        self.label_23 = QtWidgets.QLabel(self.widget)
        self.label_23.setGeometry(QtCore.QRect(1350, 180, 155, 61))
        self.label_23.setStyleSheet("border-radius:20px ;\n"
"\n"
"color: black;\n"
"font: 14pt \"Ubuntu\";\n"
"\n"
"background-color: #fdbb2d;\n"
"")
        self.label_23.setObjectName("label_23")
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setGeometry(QtCore.QRect(1350, 110, 155, 61))
        self.label_9.setStyleSheet("border-radius:20px ;\n"
"\n"
"color: black;\n"
"font: 14pt \"Ubuntu\";\n"
"\n"
"background-color: #fdbb2d;\n"
"")
        self.label_9.setObjectName("label_9")
        self.Date = QtWidgets.QLabel(self.widget)
        self.Date.setGeometry(QtCore.QRect(1510, 110, 151, 61))
        self.Date.setStyleSheet("border-radius:20px ;\n"
"\n"
"color: black;\n"
"font: 14pt \"Ubuntu\";\n"
"\n"
"background-color: #fdbb2d;\n"
"")
        self.Date.setAlignment(QtCore.Qt.AlignCenter)
        self.Date.setObjectName("Date")
        self.Status = QtWidgets.QLabel(self.widget)
        self.Status.setGeometry(QtCore.QRect(1510, 180, 151, 61))
        self.Status.setStyleSheet("border-radius:20px ;\n"
"\n"
"color: black;\n"
"font: 14pt \"Ubuntu\";\n"
"\n"
"background-color: #fdbb2d;\n"
"")
        self.Status.setObjectName("Status")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(1350, 300, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:white;\n"
"background-color: #6a6a6a;\n"
"font: 14pt \"Ubuntu\";")
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle("Kamera İzleme Ekranı")
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.AdminPanel.setText(_translate("Dialog", "Admin Paneli"))
        self.open.setText(_translate("Dialog", "Baslat"))
        self.comboBox_2.setItemText(0, _translate("Dialog", "Yüz Tanıma"))
        self.comboBox_2.setItemText(1, _translate("Dialog", "Hareket Tespit"))
        self.label.setText(_translate("Dialog", "Kameralar"))
        self.addCamera.setText(_translate("Dialog", "Ekle"))
        self.dltCamera.setText(_translate("Dialog", "Sil"))
        self.showCamera.setText(_translate("Dialog", "Göster"))
        self.label_23.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Durum</p></body></html>"))
        self.label_9.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Tarih</p></body></html>"))
        self.Date.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"/></body></html>"))
        self.Status.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_3.setText(_translate("Dialog", "Uygulama Modu"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
